### ISSUE TITLE
caused by: org.apache.sysds.runtime.DMLRuntimeException: Failed to expand list for function call (mismatching number of arguments: 3 vs. 5).

### ISSUE THREAD

**Issue by j143** [j143/systemds#133]
**DML**

```r
X = rand (rows = 50, cols = 10)
y = X %*% rand(rows = ncol(X), cols = 1)
params = list("reg", "tol", "maxi")
paramRanges = list(10^seq(0,-4), 10^seq(-5,-9), 10^seq(1,3))
[B, opt]= gridSearch(X=X, y=y, train="lm", predict="lmPredict", numB=ncol(X), params=params, paramValues=paramRanges, verbose = TRUE)
```

**Error Log**

21/05/30 06:05:35 ERROR parfor.ParWorker: Failed to execute task (type=RANGE, iterations={[i=20];[i=38];[i=1]}), retry:1
org.apache.sysds.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 0 and 0 -- Error evaluating instruction: CP°eval°lmPredict·SCALAR·STRING·true°_Var503·LIST·UNKNOWN·false°_mVar504·MATRIX·FP64
	at org.apache.sysds.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:286)
	at org.apache.sysds.runtime.controlprogram.ProgramBlock.executeInstructions(ProgramBlock.java:199)
	at org.apache.sysds.runtime.controlprogram.BasicProgramBlock.execute(BasicProgramBlock.java:125)
	at org.apache.sysds.runtime.controlprogram.parfor.ParWorker.executeRangeTask(ParWorker.java:198)
	at org.apache.sysds.runtime.controlprogram.parfor.ParWorker.executeTask(ParWorker.java:124)
	at org.apache.sysds.runtime.controlprogram.parfor.LocalParWorker.run(LocalParWorker.java:121)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.sysds.runtime.DMLRuntimeException: Failed to expand list for function call (mismatching number of arguments: 3 vs. 5).
	at org.apache.sysds.runtime.instructions.cp.EvalNaryCPInstruction.checkValidArguments(EvalNaryCPInstruction.java:231)
	at org.apache.sysds.runtime.instructions.cp.EvalNaryCPInstruction.processInstruction(EvalNaryCPInstruction.java:119)
	at org.apache.sysds.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:250)
	... 6 more

More info

```java
CP°eval°lmPredict·SCALAR·STRING·true°_Var503·LIST·UNKNOWN·false°_mVar504·MATRIX·FP64
```

**Comment by j143** [comment]
```r
X = rand (rows = 50, cols = 10)
y = X %*% rand(rows = ncol(X), cols = 1)
params = list("reg", "tol", "maxi")
paramRanges = list(10^seq(0,-4), 10^seq(-6,-12), 10^seq(1,3))
trainArgs = list(X=Xtrain, Y=ytrain, icpt=-1, reg=-1, tol=1e-9, maxi=100, maxii=-1, verbose=FALSE);
# [B, opt]= gridSearch(X=X, y=y, train="lm", predict="l2norm", numB=ncol(X), params=params, paramValues=paramRanges, verbose = TRUE)
[B, opt] = gridSearch(X=X, y=y, rain="multiLogReg", predict="accuracy", numB=ncol(X)+1,
  params=params, paramValues=paramRanges, trainArgs=trainArgs)
```

Error log

21/05/30 06:31:08 ERROR parfor.ParWorker: Failed to execute task (type=RANGE, iterations={[i=1];[i=27];[i=1]}), retry:1
org.apache.sysds.runtime.DMLRuntimeException: ERROR: Runtime error in program block generated from statement block between lines 0 and 0 -- Error evaluating instruction: CP°leftIndex°Rbeta·MATRIX·FP64°_mVar494·MATRIX·FP64°1·SCALAR·INT64·true°1·SCALAR·INT64·true°1·SCALAR·INT64·true°_Var495·SCALAR·INT64·false°_mVar496·MATRIX·FP64
	at org.apache.sysds.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:286)
	at org.apache.sysds.runtime.controlprogram.ProgramBlock.executeInstructions(ProgramBlock.java:199)
	at org.apache.sysds.runtime.controlprogram.BasicProgramBlock.execute(BasicProgramBlock.java:125)
	at org.apache.sysds.runtime.controlprogram.parfor.ParWorker.executeRangeTask(ParWorker.java:198)
	at org.apache.sysds.runtime.controlprogram.parfor.ParWorker.executeTask(ParWorker.java:124)
	at org.apache.sysds.runtime.controlprogram.parfor.LocalParWorker.run(LocalParWorker.java:121)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.sysds.runtime.DMLRuntimeException: Invalid values for matrix indexing: dimensions of the source matrix [2x10] do not match the shape of the matrix specified by indices [1:1, 1:10] (i.e., [1x10]).
	at org.apache.sysds.runtime.matrix.data.MatrixBlock.leftIndexingOperations(MatrixBlock.java:3837)
	at org.apache.sysds.runtime.matrix.data.MatrixBlock.leftIndexingOperations(MatrixBlock.java:3823)
	at org.apache.sysds.runtime.instructions.cp.MatrixIndexingCPInstruction.processInstruction(MatrixIndexingCPInstruction.java:99)
	at org.apache.sysds.runtime.controlprogram.ProgramBlock.executeSingleInstruction(ProgramBlock.java:250)
