### ISSUE TITLE
ImportError: cannot import name 'FunctionParser' from 'parser' (unknown location)

### ISSUE THREAD

**Issue by j143** [j143/systemds#169]
```console
$ systemds\src\main\python> python3 create_python_dist.py

Traceback (most recent call last):
  File "generator/generator.py", line 26, in <module>
    from parser import FunctionParser
ImportError: cannot import name 'FunctionParser' from 'parser' (unknown location)
Traceback (most recent call last):
  File "create_python_dist.py", line 25, in <module>
    subprocess.run("python3 generator/generator.py",shell=True, check=True)
  File "C:\Users\Vikalpa\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 generator/generator.py' returned non-zero exit status 1.
```

**OS:** Windows 10, Powershell

**Comment by j143** [comment]
https://github.com/j143/systemds/blob/4037b98ed0bf84ae61188f695c472246376fb445/src/main/python/generator/parser.py#L28-L73

**Comment by j143** [comment]
pre_setup instructions are incorrect.
