### ISSUE TITLE
No matching distribution found for requests>=2.24.0 (from systemds==2.1.0)

### ISSUE THREAD

**Issue by j143** [j143/systemds#173]
```console
$ python -m pip install -i https://test.pypi.org/simple/ systemds==2.1.0rc6

Collecting systemds==2.1.0rc6
  Downloading https://test-files.pythonhosted.org/packages/0d/b3/bf2c852b388895b9e4aa919b7302702aca7ce7b86d139379c87ba39c60ce/systemds-2.1.0rc6-py3-none-any.whl (207kB)
    100% |████████████████████████████████| 215kB 701kB/s 
Collecting numpy>=1.8.2 (from systemds==2.1.0rc6)
  Downloading https://test-files.pythonhosted.org/packages/4f/96/b3329750a04fcfc316f15f658daf6d81acc3ac61e3db390abe8954574c18/numpy-1.9.3.tar.gz (4.0MB)
    100% |████████████████████████████████| 4.0MB 206kB/s 
Collecting requests>=2.24.0 (from systemds==2.1.0rc6)
  Could not find a version that satisfies the requirement requests>=2.24.0 (from systemds==2.1.0rc6) (from versions: 2.5.4.1)
No matching distribution found for requests>=2.24.0 (from systemds==2.1.0rc6)
```

**OS:** Windows 10, WSL
**Python:** 3

**Comment by j143** [comment]
related: https://github.com/apache/systemds/pull/1325

**Comment by j143** [comment]
The above same command gave a different error:

```console
$ python -m pip install -i https://test.pypi.org/simple/ systemds==2.1.0rc6

Collecting systemds==2.1.0rc6
  Downloading https://test-files.pythonhosted.org/packages/0d/b3/bf2c852b388895b9e4aa919b7302702aca7ce7b86d139379c87ba39c60ce/systemds-2.1.0rc6-py3-none-any.whl (207kB)
    100% |████████████████████████████████| 215kB 562kB/s 
Collecting py4j>=0.10.9 (from systemds==2.1.0rc6)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run     
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://test.pypi.org/simple/py4j/

```

**Comment by j143** [comment]
Then install `requests==2.24.0`
