### ISSUE TITLE
AttributeError: 'SystemDSContext' object has no attribute '_SystemDSContext__stdout_thread'

### ISSUE THREAD

**Issue by j143** [j143/systemds#174]
```console

$ python

Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from systemds.context import SystemDSContext
>>> with SystemDSContext() as sds:
...     # Full generates a matrix completely filled with one number.
...     # Generate a 5x10 matrix filled with 4.2
...     m = sds.full((5, 10), 4.20)
...     # multiply with scalar. Nothing is executed yet!
...     m_res = m * 3.1
...     # Do the calculation in SystemDS by calling compute().
...     # The returned value is an numpy array that can be directly printed.
...     print(m_res.compute())
... 
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\systemds\context\systemds_context.py", line 142, in __try_startup
    self.__verify_startup(process)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\systemds\context\systemds_context.py", line 161, in __verify_startup
    raise Exception(
Exception: Exception in startup of GatewayServer: Error: Could not find or load main class org.apache.sysds.api.PythonDMLScript


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\systemds\context\systemds_context.py", line 66, in __init__
    process, port = self.__try_startup(command, port)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\systemds\context\systemds_context.py", line 146, in __try_startup
    self.close()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\systemds\context\systemds_context.py", line 224, in close
    if(self.__stdout_thread.is_alive()):
AttributeError: 'SystemDSContext' object has no attribute '_SystemDSContext__stdout_thread'
```

**Comment by j143** [comment]
check whether the `SYSTEMDS_BIN` variable set properly.
