### ISSUE TITLE
Exception in startup of GatewayServer: Error: Could not find or load main class org.apache.sysds.api.PythonDMLScript

### ISSUE THREAD

**Issue by j143** [j143/systemds#216]
<details>
  <summary> 
    <code>
      Click to see error log
    </code> 
  </summary>

```python
>>> from systemds.context import SystemDSContext
>>> with SystemDSContext() as sds:
...     # Full generates a matrix completely filled with one number.
...     # Generate a 5x10 matrix filled with 4.2
...     m = sds.full((5, 10), 4.20)
...     # multiply with scalar. Nothing is executed yet!
...     m_res = m * 3.1
...     # Do the calculation in SystemDS by calling compute().
...     # The returned value is an numpy array that can be directly printed.
...     print(m_res.compute())
... # context will automatically be closed and process stopped
... 
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/systemds/context/systemds_context.py", line 142, in __try_startup
    self.__verify_startup(process)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/systemds/context/systemds_context.py", line 161, in __verify_startup
    raise Exception(
Exception: Exception in startup of GatewayServer: Error: Could not find or load main class org.apache.sysds.api.PythonDMLScript


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/systemds/context/systemds_context.py", line 66, in __init__
    process, port = self.__try_startup(command, port)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/systemds/context/systemds_context.py", line 146, in __try_startup
    self.close()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/systemds/context/systemds_context.py", line 224, in close
    if(self.__stdout_thread.is_alive()):
AttributeError: 'SystemDSContext' object has no attribute '_SystemDSContext__stdout_thread'
```

</details>

Solution:

The .whl files does not have java libraries attached. Hence this error.

**Comment by j143** [comment]
The installed pip package does not seem to have any java files attached.

![image](https://user-images.githubusercontent.com/53068787/139596408-0b8cd6a6-aac6-437c-93ba-b0ea99f6ff2f.png)

**Comment by j143** [comment]
The size of the distribution is around **230 KB** but should be around **30 MB**

```
(systemds-env) ubuntu@ip-10-0-0-5:~/repo$ pip install -i https://test.pypi.org/simple/ systemds
Looking in indexes: https://test.pypi.org/simple/
Collecting systemds
  Downloading https://test-files.pythonhosted.org/packages/fa/5b/a40bdeb074c7b1f90a4e10ac153632c3b58ed399329e1ab03408bc5e8dbd/systemds-2.2.0-py3-none-any.whl (230 kB)
     |████████████████████████████████| 230 kB 7.0 MB/s 
```
