### ISSUE TITLE
ERROR:  While executing gem ... (Errno::EACCES) Permission denied @ rb_sysopen

### ISSUE THREAD

**Issue by j143** [j143/systemds#319]
```c
/workspaces $ gem install jekyll jekyll-redirect-from bundler pygments.rb
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /usr/local/rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/.rubocop.yml
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/package.rb:448:in `initialize'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/package.rb:448:in `open'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/package.rb:448:in `block (2 levels) in extract_tar_gz'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/package/tar_reader.rb:60:in `each'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/package.rb:415:in `block in extract_tar_gz'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/package.rb:541:in `block in open_tar_gz'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/package.rb:538:in `wrap'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/package.rb:538:in `open_tar_gz'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/package.rb:414:in `extract_tar_gz'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/package.rb:392:in `block (2 levels) in extract_files'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/package/tar_reader.rb:60:in `each'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/package.rb:389:in `block in extract_files'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/package/file_source.rb:29:in `open'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/package/file_source.rb:29:in `with_read_io'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/package.rb:386:in `extract_files'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/installer.rb:852:in `extract_files'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/installer.rb:324:in `install'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/resolver/specification.rb:104:in `install'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/request_set.rb:194:in `block in install'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/request_set.rb:182:in `each'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/request_set.rb:182:in `install'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/commands/install_command.rb:214:in `install_gem'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/commands/install_command.rb:230:in `block in install_gems'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/commands/install_command.rb:223:in `each'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/commands/install_command.rb:223:in `install_gems'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/commands/install_command.rb:169:in `execute'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/command.rb:327:in `invoke_with_build_args'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/command_manager.rb:252:in `invoke_command'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/command_manager.rb:192:in `process_args'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/command_manager.rb:150:in `run'
        /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/gem_runner.rb:51:in `run'
        /usr/local/rvm/rubies/ruby-3.2.2/bin/gem:10:in `<main>'
```

**Comment by j143** [comment]
install with sudo,

```c
/workspaces $ sudo gem install jekyll jekyll-redirect-from bundler pygments.rb
Successfully installed jekyll-4.3.3
Parsing documentation for jekyll-4.3.3
Done installing documentation for jekyll after 1 seconds
Fetching jekyll-redirect-from-0.16.0.gem
Successfully installed jekyll-redirect-from-0.16.0
Parsing documentation for jekyll-redirect-from-0.16.0
Installing ri documentation for jekyll-redirect-from-0.16.0
Done installing documentation for jekyll-redirect-from after 0 seconds
Fetching bundler-2.5.6.gem
Successfully installed bundler-2.5.6
Parsing documentation for bundler-2.5.6
Installing ri documentation for bundler-2.5.6
Done installing documentation for bundler after 0 seconds
Fetching pygments.rb-2.4.1.gem
Successfully installed pygments.rb-2.4.1
Parsing documentation for pygments.rb-2.4.1
Installing ri documentation for pygments.rb-2.4.1
Done installing documentation for pygments.rb after 0 seconds
4 gems installed

A new release of RubyGems is available: 3.4.10 → 3.5.6!
Run `gem update --system 3.5.6` to update your installation.
```
