### ISSUE TITLE
error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by j143** [j143/systemds#320]
```c
error: invalid command 'bdist_wheel'
Traceback (most recent call last):
  File "/workspaces/systemds/src/main/python/create_python_dist.py", line 28, in <module>
    subprocess.run("python3 setup.py sdist bdist_wheel",shell=True, check=True)
  File "/home/codespace/.python/current/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 setup.py sdist bdist_wheel' returned non-zero exit status 1.
ERROR    InvalidDistribution: Cannot find file (or expand pattern): 'dist/*'                                                                                          
ERROR    InvalidDistribution: Cannot find file (or expand pattern): 'dist/*'                                                                                          
@j143 ➜ /workspaces/systemds (1130afe0f3) $ cd ..
@j143 ➜ /workspaces $ pip install bdist_wheel
ERROR: Could not find a version that satisfies the requirement bdist_wheel (from versions: none)
ERROR: No matching distribution found for bdist_wheel

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python -m pip install --upgrade pip
```

**Comment by j143** [comment]
Install `wheel` first, to enable the `bdist_wheel` subcommand

```
/workspaces $ pip install wheel
Collecting wheel
  Downloading wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
Downloading wheel-0.43.0-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 kB 690.8 kB/s eta 0:00:00
Installing collected packages: wheel
Successfully installed wheel-0.43.0

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python -m pip install --upgrade pip
```
