### ISSUE TITLE
Error: Node Sass does not yet support your current environment

### ISSUE THREAD

**Issue by j143** [j143/systemds#322]
```
$ gulp
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (115)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v8.0.0
    at module.exports (/workspaces/systemds-website/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/workspaces/systemds-website/node_modules/node-sass/lib/index.js:13:35)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/workspaces/systemds-website/gulpfile.js:4:35)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
```

**Comment by j143** [comment]
https://stackoverflow.com/questions/37324519/node-sass-does-not-yet-support-your-current-environment-linux-64-bit-with-false

suggests to use

```bash
npm rebuild node-sass
```

we shall see:

```bash
$ npm rebuild node-sass
rebuilt dependencies successfully
```
