### ISSUE TITLE
keyring.errors.NoKeyringError: No recommended backend was available

### ISSUE THREAD

**Issue by j143** [j143/systemds#323]
```c
WARNING  Error getting password from keyring                                                                                                                            
         Traceback (most recent call last):                                                                                                                             
           File "/usr/local/python/3.10.13/lib/python3.10/site-packages/twine/auth.py", line 81, in get_password_from_keyring                                           
             return cast(str, keyring.get_password(system, username))                                                                                                   
           File "/usr/local/python/3.10.13/lib/python3.10/site-packages/keyring/core.py", line 56, in get_password                                                      
             return get_keyring().get_password(service_name, username)                                                                                                  
           File "/usr/local/python/3.10.13/lib/python3.10/site-packages/keyring/backends/fail.py", line 28, in get_password                                             
             raise NoKeyringError(msg)                                                                                                                                  
         keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if  
         you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.                                                                
Enter your API token: 
Uploading systemds-3.2.0-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.3/74.3 MB • 00:04 • 22.4 MB/s
WARNING  Error during upload. Retry with the --verbose option for more details.                                                                                         
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/                                                                                                  
         File already exists. See https://test.pypi.org/help/#file-name-reuse for more information
```

**Comment by j143** [comment]
Is the project version is already published? -- versioned releases could not be changed. No force writes are allowed!
