### ISSUE TITLE
Error: Could not find or load main class org.apache.sysds.api.DMLScript

### ISSUE THREAD

**Issue by j143** [j143/systemds#79]
On windows use `;` as a java classpath separator. In Linux it is `:`.

```sh
# on windows
java -cp 'target/SystemDS.jar;target/lib/*' org.apache.sysds.api.DMLScript -s "print('hello')"
```

```sh
# on linux
java -cp 'target/SystemDS.jar:target/lib/*' org.apache.sysds.api.DMLScript -s "print('hello')"
```
---
**On windows 10:**
```sh
systemds/target > java -cp "./lib/*:systemds-2.1.0.jar" org.apache.sysds.api.DMLScript -s "print('hello')"
```
or 

```sh
java -Xmx4g -Xms4g -Xmn400m -cp target/SystemDS.jar:target/lib/*:target/SystemDS-*.jar org.apache.sysds.api.DMLScript -f ../main.dml -exec singlenode -gpu
```

Error: Could not find or load main class org.apache.sysds.api.DMLScript

More info:

```
$ ls
d-----        5/20/2021   5:33 PM                antrun
d-----        5/20/2021   5:32 PM                classes
d-----        5/20/2021   5:33 PM                dependency-maven-plugin-markers
d-----        5/20/2021   5:32 PM                generated-sources
d-----        5/20/2021   5:33 PM                hadoop-test
d-----        5/20/2021   5:33 PM                lib
d-----        5/20/2021   5:33 PM                maven-archiver
d-----        5/20/2021   5:32 PM                maven-shared-archive-resources
d-----        5/20/2021   5:32 PM                maven-status
d-----        5/20/2021   5:32 PM                test-classes
-a----        5/20/2021   5:32 PM             30 .plxarc
-a----        5/20/2021   5:33 PM        6609152 systemds-2.1.0-shaded.jar
-a----        5/20/2021   5:33 PM        6609152 systemds-2.1.0.jar
-a----        5/20/2021   5:33 PM        6609152 SystemDS.jar
```

_Originally posted by @j143 in https://github.com/j143/systemds/issues/78#issuecomment-845041718_

**Comment by j143** [comment]
If only the SystemDs.jar is provided then

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more

Traceback (most recent call last):
  File "D:\repo\validate\venv\lib\site-packages\py4j\java_gateway.py", line 1132, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\repo\validate\test.py", line 14, in <module>
    with SystemDSContext() as sds:
  File "D:\repo\validate\venv\lib\site-packages\systemds\context\systemds_context.py", line 82, in __init__
    self.__start(port,  capture_stdout)
  File "D:\repo\validate\venv\lib\site-packages\systemds\context\systemds_context.py", line 273, in __start
    self.__start(-1, capture_stdout, retry + 1)
  File "D:\repo\validate\venv\lib\site-packages\systemds\context\systemds_context.py", line 273, in __start
    self.__start(-1, capture_stdout, retry + 1)
  File "D:\repo\validate\venv\lib\site-packages\systemds\context\systemds_context.py", line 273, in __start
    self.__start(-1, capture_stdout, retry + 1)
  [Previous line repeated 1 more time]
  File "D:\repo\validate\venv\lib\site-packages\systemds\context\systemds_context.py", line 233, in __start
    raise Exception(
Exception: Failed startup of SystemDS Context with 3 repeats
```
