### ISSUE TITLE
The git-push command failed. Missing or invalid credentials. vscode-git

### ISSUE THREAD

**Issue by j143** [j143/systemds#98]
[ERROR] Command output:
[ERROR] Missing or invalid credentials.
[ERROR] Error: connect ECONNREFUSED /tmp/vscode-git-582b2f940f.sock
[ERROR]     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
[ERROR]   errno: -111,
[ERROR]   code: 'ECONNREFUSED',
[ERROR]   syscall: 'connect',
[ERROR]   address: '/tmp/vscode-git-582b2f940f.sock'
[ERROR] }
[ERROR] Missing or invalid credentials.
[ERROR] Error: connect ECONNREFUSED /tmp/vscode-git-582b2f940f.sock
[ERROR]     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
[ERROR]   errno: -111,
[ERROR]   code: 'ECONNREFUSED',
[ERROR]   syscall: 'connect',
[ERROR]   address: '/tmp/vscode-git-582b2f940f.sock'
[ERROR] }
[ERROR] remote: No anonymous write access.
[ERROR] fatal: Authentication failed for 'https://github.com/j143/systemds.git/'

**solution:**

make sure the git extension is loaded, else reload the window.
![image](https://user-images.githubusercontent.com/53068787/119289194-c0f70680-bc67-11eb-8756-8fd8b0daf8c4.png)

discussion: https://github.com/j143/systemds/issues/98#issuecomment-846685684

**Comment by j143** [comment]
This error is temporary. The `git push` works fine the next time.

**Comment by j143** [comment]
Few tries about solving this problem:

1. Forget all the cached credentials
https://git-scm.com/docs/git-credential-cache#_controlling_the_daemon

```sh
git credential-cache exit

```

**Comment by j143** [comment]
logs

```diff
Resolving wsl+ubuntu, resolveAttempt: 1
[2021-05-24 00:42:43.207] Starting VS Code Server inside WSL (Ubuntu)
[2021-05-24 00:42:43.207] Extension version: 0.44.5, Windows build: 18363. Multi distro support: available. WSL path support: enabled
[2021-05-24 00:42:43.859] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Ubuntu -e sh -c "[ -d ~/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2021-05-24 00:42:44.770] Probing result: found
[2021-05-24 00:42:44.770] Server install found in WSL
[2021-05-24 00:42:44.779] Launching C:\WINDOWS\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 054a9295330880ed74ceaedda236253b4f39a335 stable .vscode-server 0  --disable-telemetry' in c:\Users\windows-user\.vscode\extensions\ms-vscode-remote.remote-wsl-0.44.5}
+ [2021-05-24 00:42:46.914] Setting up server environment: Looking for /home/user/.vscode-server/server-env-setup. Not found.
[2021-05-24 00:42:46.914] WSL version: 4.4.0-18362-Microsoft Ubuntu
[2021-05-24 00:42:46.914] Starting server: /home/user/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/server.sh  --port=0 --use-host-proxy --fileWatcherPolling=0 --disable-telemetry

```

make sure the git is loaded

![image](https://user-images.githubusercontent.com/53068787/119288706-b6883d00-bc66-11eb-8805-f724fe7aef07.png)
